### ISSUE TITLE
When will you release the code and data?

### ISSUE THREAD

**Issue by JarvisUSTC** [PandragonXIII/CIDER#1]

**Comment by PandragonXIII** [comment]
Thanks for your attention! To be honest, I'm not sure about the exact date. But I'll try to finish organizing and upload in a month.

**Comment by JarvisUSTC** [comment]
Thank you! I’m looking forward to it whenever you’re ready.

**Comment by PandragonXIII** [comment]
The code has been released! If you have any questions, please feel free to post them.
